runtime: python37

env_variables:
  GCP_PROJECT: "fansipan-website-290191"
  GCS_BUCKET: "fansipan-website-290191"
  FIREBASE_CONFIG: "firebase_config.json"

handlers:
  - url: /static
    static_dir: static
  
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301